part of 'kaye_maneuver_electrify.dart';

class KayeManeuverElectrifyFootstep extends _KayeManeuverElectrifyFootstep {
  const KayeManeuverElectrifyFootstep({required super.args});

  static const kType = 'kaye_maneuver_electrify';

  @override
  String get type => kType;

  static KayeManeuverElectrifyFootstep fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => KayeManeuverElectrifyFootstep(args: map);

  @override
  KayeManeuverElectrifyFootstepGoggles createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = KayeManeuverElectrifyFootstepGoggles.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  KayeManeuverElectrify buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return KayeManeuverElectrify(
      borderRadius: model.borderRadius,
      colorFrom: model.colorFrom,
      colorTo: model.colorTo,
      height: model.height,
      key: key,
      onTap: model.onTap,
      radius: model.radius,
      title: model.title,
      titleColor: model.titleColor,
      titleFontSize: model.titleFontSize,
      titleFontWeight: model.titleFontWeight,
      width: model.width,
      child: model.child?.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonKayeManeuverElectrify extends JsonWidgetData {
  JsonKayeManeuverElectrify({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.borderRadius,
    this.colorFrom = KayeAdvertise.kayeDutchEnforceDirtManeuver,
    this.colorTo = KayeAdvertise.kayeDutchEnforceToManeuver,
    required this.height,
    required this.onTap,
    this.radius,
    this.title,
    this.titleColor = Colors.white,
    this.titleFontSize = 16,
    this.titleFontWeight = FontWeight.bold,
    required this.width,
    this.child,
  }) : super(
         jsonWidgetArgs: KayeManeuverElectrifyFootstepGoggles.fromDynamic(
           {
             'borderRadius': borderRadius,
             'colorFrom': colorFrom,
             'colorTo': colorTo,
             'height': height,
             'onTap': onTap,
             'radius': radius,
             'title': title,
             'titleColor': titleColor,
             'titleFontSize': titleFontSize,
             'titleFontWeight': titleFontWeight,
             'width': width,
             'child': child,
             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => KayeManeuverElectrifyFootstep(
           args: KayeManeuverElectrifyFootstepGoggles.fromDynamic(
             {
               'borderRadius': borderRadius,
               'colorFrom': colorFrom,
               'colorTo': colorTo,
               'height': height,
               'onTap': onTap,
               'radius': radius,
               'title': title,
               'titleColor': titleColor,
               'titleFontSize': titleFontSize,
               'titleFontWeight': titleFontWeight,
               'width': width,
               'child': child,
               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: KayeManeuverElectrifyFootstep.kType,
       );

  final BorderRadius? borderRadius;

  final Color colorFrom;

  final Color colorTo;

  final double height;

  final void Function()? onTap;

  final double? radius;

  final String? title;

  final Color titleColor;

  final double? titleFontSize;

  final FontWeight? titleFontWeight;

  final double width;

  final JsonWidgetData? child;
}

/* AUTOGENERATED FROM [KayeManeuverElectrify]*/
class KayeManeuverElectrifyFootstepGoggles extends JsonWidgetBuilderModel {
  const KayeManeuverElectrifyFootstepGoggles(
    super.args, {
    this.borderRadius,
    this.colorFrom = KayeAdvertise.kayeDutchEnforceDirtManeuver,
    this.colorTo = KayeAdvertise.kayeDutchEnforceToManeuver,
    required this.height,
    required this.onTap,
    this.radius,
    this.title,
    this.titleColor = Colors.white,
    this.titleFontSize = 16,
    this.titleFontWeight = FontWeight.bold,
    required this.width,
    this.child,
  });

  final BorderRadius? borderRadius;

  final Color colorFrom;

  final Color colorTo;

  final double height;

  final void Function()? onTap;

  final double? radius;

  final String? title;

  final Color titleColor;

  final double? titleFontSize;

  final FontWeight? titleFontWeight;

  final double width;

  final JsonWidgetData? child;

  static KayeManeuverElectrifyFootstepGoggles fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[KayeManeuverElectrifyFootstep]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static KayeManeuverElectrifyFootstepGoggles? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    KayeManeuverElectrifyFootstepGoggles? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is KayeManeuverElectrifyFootstepGoggles) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = KayeManeuverElectrifyFootstepGoggles(
          args,
          borderRadius: () {
            dynamic parsed = ThemeDecoder.decodeBorderRadius(
              map['borderRadius'],
              validate: false,
            );

            return parsed;
          }(),
          colorFrom: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['colorFrom'],
              validate: false,
            );
            parsed ??= KayeAdvertise.kayeDutchEnforceDirtManeuver;

            return parsed;
          }(),
          colorTo: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['colorTo'],
              validate: false,
            );
            parsed ??= KayeAdvertise.kayeDutchEnforceToManeuver;

            return parsed;
          }(),
          height: () {
            dynamic parsed = JsonClass.parseDouble(map['height']);

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [height].',
              );
            }
            return parsed;
          }(),
          onTap: map['onTap'],
          radius: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['radius']);

            return parsed;
          }(),
          title: map['title'],
          titleColor: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['titleColor'],
              validate: false,
            );
            parsed ??= Colors.white;

            return parsed;
          }(),
          titleFontSize: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['titleFontSize']);

            if (!map.containsKey('titleFontSize')) {
              parsed ??= 16.0;
            }

            return parsed;
          }(),
          titleFontWeight: () {
            dynamic parsed = ThemeDecoder.decodeFontWeight(
              map['titleFontWeight'],
              validate: false,
            );
            if (!map.containsKey('titleFontWeight')) {
              parsed ??= FontWeight.bold;
            }

            return parsed;
          }(),
          width: () {
            dynamic parsed = JsonClass.parseDouble(map['width']);

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [width].',
              );
            }
            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['child'],
              registry: registry,
            );

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'borderRadius': ThemeEncoder.encodeBorderRadius(borderRadius),
      'colorFrom': KayeAdvertise.kayeDutchEnforceDirtManeuver == colorFrom
          ? null
          : ThemeEncoder.encodeColor(colorFrom),
      'colorTo': KayeAdvertise.kayeDutchEnforceToManeuver == colorTo
          ? null
          : ThemeEncoder.encodeColor(colorTo),
      'height': height,
      'onTap': onTap,
      'radius': radius,
      'title': title,
      'titleColor': Colors.white == titleColor
          ? null
          : ThemeEncoder.encodeColor(titleColor),
      'titleFontSize': 16 == titleFontSize ? null : titleFontSize,
      'titleFontWeight': FontWeight.bold == titleFontWeight
          ? null
          : ThemeEncoder.encodeFontWeight(titleFontWeight),
      'width': width,
      'child': child?.toJson(),
      ...args,
    });
  }
}

class KayeManeuverElectrifyVomit {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/kaye/kaye_maneuver_electrify.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'KayeManeuverElectrify',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'borderRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'colorFrom': SchemaHelper.objectSchema(ColorSchema.id),
      'colorTo': SchemaHelper.objectSchema(ColorSchema.id),
      'height': SchemaHelper.numberSchema,
      'onTap': SchemaHelper.anySchema,
      'radius': SchemaHelper.numberSchema,
      'title': SchemaHelper.stringSchema,
      'titleColor': SchemaHelper.objectSchema(ColorSchema.id),
      'titleFontSize': SchemaHelper.numberSchema,
      'titleFontWeight': SchemaHelper.objectSchema(FontWeightSchema.id),
      'width': SchemaHelper.numberSchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': ['height', 'onTap', 'width'],
  };
}
