part of 'kaye_sydney_electrify.dart';

class KayeSydneyElectrifyFootstep extends _KayeSydneyElectrifyFootstep {
  const KayeSydneyElectrifyFootstep({required super.args});

  static const kType = 'kaye_sydney_electrify';

  @override
  String get type => kType;

  static KayeSydneyElectrifyFootstep fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => KayeSydneyElectrifyFootstep(args: map);

  @override
  KayeSydneyElectrifyFootstepGoggles createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = KayeSydneyElectrifyFootstepGoggles.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  KayeSydneyElectrify buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return KayeSydneyElectrify(
      borderRadius: model.borderRadius,
      color: model.color,
      fit: model.fit,
      height: model.height,
      highlightColor: model.highlightColor,
      key: key,
      onTap: model.onTap,
      splashColor: model.splashColor,
      url: model.url,
      width: model.width,
    );
  }
}

class JsonKayeSydneyElectrify extends JsonWidgetData {
  JsonKayeSydneyElectrify({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.borderRadius,
    this.color = Colors.transparent,
    this.fit = BoxFit.contain,
    this.height,
    this.highlightColor,
    this.onTap,
    this.splashColor,
    required this.url,
    this.width,
  }) : super(
         jsonWidgetArgs: KayeSydneyElectrifyFootstepGoggles.fromDynamic(
           {
             'borderRadius': borderRadius,
             'color': color,
             'fit': fit,
             'height': height,
             'highlightColor': highlightColor,
             'onTap': onTap,
             'splashColor': splashColor,
             'url': url,
             'width': width,
             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder: () => KayeSydneyElectrifyFootstep(
           args: KayeSydneyElectrifyFootstepGoggles.fromDynamic(
             {
               'borderRadius': borderRadius,
               'color': color,
               'fit': fit,
               'height': height,
               'highlightColor': highlightColor,
               'onTap': onTap,
               'splashColor': splashColor,
               'url': url,
               'width': width,
               ...args,
             },
             args: args,
             registry: registry,
           ),
         ),
         jsonWidgetType: KayeSydneyElectrifyFootstep.kType,
       );

  final BorderRadius? borderRadius;

  final Color? color;

  final BoxFit? fit;

  final double? height;

  final Color? highlightColor;

  final void Function()? onTap;

  final Color? splashColor;

  final String url;

  final double? width;
}

/* AUTOGENERATED FROM [KayeSydneyElectrify]*/
class KayeSydneyElectrifyFootstepGoggles extends JsonWidgetBuilderModel {
  const KayeSydneyElectrifyFootstepGoggles(
    super.args, {
    this.borderRadius,
    this.color = Colors.transparent,
    this.fit = BoxFit.contain,
    this.height,
    this.highlightColor,
    this.onTap,
    this.splashColor,
    required this.url,
    this.width,
  });

  final BorderRadius? borderRadius;

  final Color? color;

  final BoxFit? fit;

  final double? height;

  final Color? highlightColor;

  final void Function()? onTap;

  final Color? splashColor;

  final String url;

  final double? width;

  static KayeSydneyElectrifyFootstepGoggles fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[KayeSydneyElectrifyFootstep]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static KayeSydneyElectrifyFootstepGoggles? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    KayeSydneyElectrifyFootstepGoggles? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is KayeSydneyElectrifyFootstepGoggles) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = KayeSydneyElectrifyFootstepGoggles(
          args,
          borderRadius: () {
            dynamic parsed = ThemeDecoder.decodeBorderRadius(
              map['borderRadius'],
              validate: false,
            );

            return parsed;
          }(),
          color: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['color'],
              validate: false,
            );
            if (!map.containsKey('color')) {
              parsed ??= Colors.transparent;
            }

            return parsed;
          }(),
          fit: () {
            dynamic parsed = ThemeDecoder.decodeBoxFit(
              map['fit'],
              validate: false,
            );
            if (!map.containsKey('fit')) {
              parsed ??= BoxFit.contain;
            }

            return parsed;
          }(),
          height: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['height']);

            return parsed;
          }(),
          highlightColor: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['highlightColor'],
              validate: false,
            );

            return parsed;
          }(),
          onTap: map['onTap'],
          splashColor: () {
            dynamic parsed = ThemeDecoder.decodeColor(
              map['splashColor'],
              validate: false,
            );

            return parsed;
          }(),
          url: map['url'],
          width: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['width']);

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'borderRadius': ThemeEncoder.encodeBorderRadius(borderRadius),
      'color': Colors.transparent == color
          ? null
          : ThemeEncoder.encodeColor(color),
      'fit': BoxFit.contain == fit ? null : ThemeEncoder.encodeBoxFit(fit),
      'height': height,
      'highlightColor': ThemeEncoder.encodeColor(highlightColor),
      'onTap': onTap,
      'splashColor': ThemeEncoder.encodeColor(splashColor),
      'url': url,
      'width': width,
      ...args,
    });
  }
}

class KayeSydneyElectrifyVomit {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/kaye/kaye_sydney_electrify.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'KayeSydneyElectrify',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'borderRadius': SchemaHelper.objectSchema(BorderRadiusSchema.id),
      'color': SchemaHelper.objectSchema(ColorSchema.id),
      'fit': SchemaHelper.objectSchema(BoxFitSchema.id),
      'height': SchemaHelper.numberSchema,
      'highlightColor': SchemaHelper.objectSchema(ColorSchema.id),
      'onTap': SchemaHelper.anySchema,
      'splashColor': SchemaHelper.objectSchema(ColorSchema.id),
      'url': SchemaHelper.stringSchema,
      'width': SchemaHelper.numberSchema,
    },
    'required': ['url'],
  };
}
