name: pag
description: PAG for flutter
version: 1.0.9+flutter3.29
homepage: https://github.com/libpag/pag-flutter

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_pag_plugin
        pluginClass: FlutterPagPlugin
      ios:
        pluginClass: FlutterPagPlugin
      ohos:
        package: com.tencent.flutter_pag_plugin
        pluginClass: FlutterPagPlugin  


