#If you need to build a test package, use the following command to create keystore.jks in android dir, config uncomment properties.
#keytool -genkey -v -keystore keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias keyAlias
#storePassword=kaye_belgian_fight
#keyAlias=kaye_belgian_nature
#storeFile=../keystore.jks
#storeFile=../keystore.jks
